'use client';
import { useCallback, useState } from 'react';
import { RoundHeader } from './round-header';
import { CodeEditor } from '@/components/shared/code-editor';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { mockDebuggingProblems } from '@/lib/mock-data';
import { Play, Send } from 'lucide-react';
import { useAntiCheat } from '@/hooks/use-anti-cheat';
import { useRouter } from 'next/navigation';
import { ScrollArea } from '../ui/scroll-area';
import type { Team, DebuggingProblem } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';

export function DebuggingView() {
  const [rulesAccepted, setRulesAccepted] = useState(false);
  const router = useRouter();
  const { toast } = useToast();
  const [problem, setProblem] = useState<DebuggingProblem | null>(null);
  const [code, setCode] = useState('');
  const [output, setOutput] = useState(
    'Click "Run Code" to see the output here.'
  );
  const [showResultDialog, setShowResultDialog] = useState(false);
  const [isSolutionCorrect, setIsSolutionCorrect] = useState(false);
  const [isRunning, setIsRunning] = useState(false);

  const handleLanguageSelect = (lang: 'python' | 'java') => {
    const allProblemsForLang = mockDebuggingProblems.filter((p) => p.language === lang);
    const assignedProblemIdsStr = localStorage.getItem('assignedDebugProblems');
    let assignedProblemIds: string[] = assignedProblemIdsStr ? JSON.parse(assignedProblemIdsStr) : [];
    let unassignedProblems = allProblemsForLang.filter(p => !assignedProblemIds.includes(p.id));

    if (unassignedProblems.length === 0) {
      unassignedProblems = allProblemsForLang;
      assignedProblemIds = [];
    }
    
    const randomProblem = unassignedProblems[Math.floor(Math.random() * unassignedProblems.length)];
    
    if (randomProblem) {
      assignedProblemIds.push(randomProblem.id);
      localStorage.setItem('assignedDebugProblems', JSON.stringify(assignedProblemIds));
      setProblem(randomProblem);
      setCode(randomProblem.buggyCode);
    }
  };

  const handleRunCode = () => {
    if (!problem) return;
    setIsRunning(true);
    setOutput('Compiling and running tests...');

    // Simulate a very fast execution (150ms)
    setTimeout(() => {
      const normalizedUserCode = code.replace(/\s+/g, '');
      const normalizedBuggyCode = problem.buggyCode.replace(/\s+/g, '');
      const normalizedSolutionCode = problem.solutionCode.replace(/\s+/g, '');

      if (normalizedUserCode === normalizedBuggyCode) {
        setOutput(problem.buggyOutput || 'Error: Output does not match the expected result. Please check for logical or syntax errors.');
      } else if (normalizedUserCode === normalizedSolutionCode) {
        setOutput('Success! All test cases passed.\n\nOutput:\nProgram executed successfully with the correct logic.');
      } else {
        setOutput('Runtime Error: The output generated by your code does not match the expected result. Keep debugging!');
      }
      setIsRunning(false);
    }, 150);
  };

  const endRound = useCallback(
    (isCorrect: boolean) => {
      const score = isCorrect ? 100 : 0;
      const teamData = localStorage.getItem('currentTeam');
      if (teamData) {
        const currentTeam: Team = JSON.parse(teamData);
        const newTotalScore = (currentTeam.score || 0) + score;

        const leaderboardStr = localStorage.getItem('liveLeaderboard');
        let leaderboard: Team[] = leaderboardStr ? JSON.parse(leaderboardStr) : [];
        const teamIndex = leaderboard.findIndex((t) => t.id === currentTeam.id);
        if (teamIndex !== -1) {
          leaderboard[teamIndex].score = newTotalScore;
        }

        localStorage.setItem('liveLeaderboard', JSON.stringify(leaderboard));
        localStorage.setItem('currentTeam', JSON.stringify({ ...currentTeam, score: newTotalScore }));
      }

      const completedRounds = JSON.parse(localStorage.getItem('completedRounds') || '[]');
      if (!completedRounds.includes('2')) {
        completedRounds.push('2');
        localStorage.setItem('completedRounds', JSON.stringify(completedRounds));
      }
      router.push('/dashboard');
    },
    [router]
  );

  const handleSubmit = () => {
    if (!problem) return;
    const isCorrect = code.replace(/\s+/g, '') === problem.solutionCode.replace(/\s+/g, '');
    setIsSolutionCorrect(isCorrect);
    setShowResultDialog(true);
  };

  const handleFinish = useCallback(() => {
    toast({ title: "Time's Up!", description: 'Your solution is being submitted automatically.' });
    endRound(false);
  }, [endRound, toast]);

  const handleWarning = useCallback(
    (warningCount: number) => {
      if (warningCount >= 3) {
        toast({
          variant: 'destructive',
          title: 'Disqualified',
          description: 'Maximum warnings reached. Your test is being submitted.',
        });
        endRound(false);
      }
    },
    [endRound, toast]
  );

  useAntiCheat(handleWarning);

  if (!rulesAccepted) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-background via-gray-900/50 to-background p-4">
        <Card className="w-full max-w-4xl animate-fade-in">
          <CardHeader>
            <CardTitle className="font-headline text-3xl text-center">
              Debugging Round – Official Rules & Guidelines
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[60vh] pr-6">
              <div className="prose prose-invert max-w-none font-body text-muted-foreground">
                <h3>1. Time Limit Rule</h3>
                <p><strong>Rule:</strong> Each team will be given 15 minutes to debug the problems.</p>
                <ul>
                  <li>3–5 debugging questions (assigned randomly).</li>
                  <li>Each question contains intentional syntax, logical, or runtime errors.</li>
                  <li>Submission after time ends will not be accepted.</li>
                </ul>

                <hr />

                <h3>2. No Internet / No AI Rule</h3>
                <p><strong>Rule:</strong> Participants are not allowed to use external resources like Google, ChatGPT, or AI tools.</p>
                <p><strong>Switching tabs or windows will result in a warning. Three warnings will lead to automatic submission.</strong></p>

                <hr />

                <h3>3. No Changing Logic Rule</h3>
                <p><strong>Rule:</strong> Participants must fix only errors, not rewrite the entire program.</p>

                <hr />

                <h3>4. Output Must Match Exactly</h3>
                <p><strong>Rule:</strong> Program output must match the expected output exactly.</p>

                <hr />

                <h3>5. Marking Criteria Rule</h3>
                <table>
                  <thead>
                    <tr><th>Criteria</th><th>Marks</th></tr>
                  </thead>
                  <tbody>
                    <tr><td>Syntax Error Fix</td><td>30%</td></tr>
                    <tr><td>Logical Error Fix</td><td>30%</td></tr>
                    <tr><td>Runtime Error Fix</td><td>20%</td></tr>
                    <tr><td>Code Cleanliness</td><td>10%</td></tr>
                    <tr><td>Time of Submission</td><td>10%</td></tr>
                  </tbody>
                </table>

                <hr />

                <h3>6. Tie-Breaker Rule 🏆</h3>
                <p>If two teams get equal marks:</p>
                <ol>
                  <li>Earlier submission wins.</li>
                  <li>Fewer compilation attempts wins.</li>
                </ol>
              </div>
            </ScrollArea>
            <Button onClick={() => setRulesAccepted(true)} className="w-full mt-8">
              I Understand and Agree, Start Round
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!problem) {
    return (
      <div className="flex flex-col h-screen font-code">
        <RoundHeader round={2} title="Debugging Round" countdownDuration={15 * 60} onFinish={handleFinish} />
        <div className="flex-1 flex items-center justify-center bg-gradient-to-br from-background via-gray-900/50 to-background">
          <Card className="w-full max-w-md animate-fade-in">
            <CardHeader>
              <CardTitle className="font-headline text-2xl text-center">Choose Your Language</CardTitle>
            </CardHeader>
            <CardContent className="flex justify-center gap-4">
              <Button onClick={() => handleLanguageSelect('python')} className="text-lg py-6 px-12">Python</Button>
              <Button onClick={() => handleLanguageSelect('java')} variant="secondary" className="text-lg py-6 px-12">Java</Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-screen font-code">
      <RoundHeader round={2} title="Debugging Round" countdownDuration={15 * 60} onFinish={handleFinish} />
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-4 p-4 overflow-auto">
        <div className="flex flex-col gap-4">
          <Card className="flex-1 flex flex-col">
            <CardHeader><CardTitle className="font-headline">{problem.title}</CardTitle></CardHeader>
            <CardContent className="flex-1 flex flex-col gap-4">
              <p className="font-body text-muted-foreground">{problem.description}</p>
              <div className="flex-1 bg-background rounded-md p-4 overflow-auto text-sm border">
                <pre><code>{problem.buggyCode}</code></pre>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-4">
            <Select value={problem.language} disabled>
              <SelectTrigger className="w-[180px]"><SelectValue placeholder="Select Language" /></SelectTrigger>
              <SelectContent><SelectItem value="python">Python</SelectItem><SelectItem value="java">Java</SelectItem></SelectContent>
            </Select>
            <div className="flex-1" />
            <Button variant="secondary" onClick={handleRunCode} disabled={isRunning}>
              <Play className="mr-2 h-4 w-4" /> {isRunning ? 'Running...' : 'Run Code'}
            </Button>
            <Button onClick={handleSubmit} className="bg-accent hover:bg-accent/90 text-accent-foreground">
              <Send className="mr-2 h-4 w-4" /> Submit
            </Button>
          </div>
          <div className="flex-1 grid grid-rows-2 gap-4">
            <CodeEditor code={code} onCodeChange={setCode} language={problem.language} />
            <Card className="flex flex-col">
              <CardHeader><CardTitle className="font-headline text-lg">Output Console</CardTitle></CardHeader>
              <CardContent className="flex-1 bg-background rounded-b-md p-4 overflow-auto">
                <pre className={`text-sm whitespace-pre-wrap ${output.includes('Success') ? 'text-green-400' : 'text-muted-foreground'}`}>{output}</pre>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <AlertDialog open={showResultDialog} onOpenChange={setShowResultDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="text-2xl font-headline">Round Submitted</AlertDialogTitle>
            <AlertDialogDescription className="text-lg">
              {isSolutionCorrect ? 'Excellent work! Your solution is correct.' : 'Your solution has been submitted. The round is now over.'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogAction onClick={() => endRound(isSolutionCorrect)}>Continue to Dashboard</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
